home/urls.py
from django.conf.urls import patterns, url

from generic.models import *
from generic.views import *

from home import views

urlpatterns = patterns('',
                       url(r'^$', views.index, name='index'),
                       url(r'^home/?', views.index, name='index'),
                       url(r'^check_user/?', check_user),
                       url(r'^search_orgs/?', search_orgs),
                       url(r'^get_signators/?', get_signators))

sos_grant/urls.py
from django.conf.urls import patterns, include, url
from . import views

app_name = 'sos_grant'
urlpatterns = patterns(
    '',
    url(r'^$', views.index, name='index'),
    url(r'my_application/?$',
        views.manage_application,
        name='manage_application'),
    url(r'my_application/create/?$',
        views.create_application,
        name='create_application'),
    url(r'my_application/edit/?$',
        views.edit_application,
        name='edit_application'),
    url(r'my_application/delete/?$',
        views.delete_application,
        name='delete_application'),
    #admin urls
    url(r'^admin/?$', views.admin_index, name='admin_index'),
    url(r'^admin/create/?$',
        views.admin_create_grant_date,
        name='admin_create_grant_date'),
    url(r'^admin/edit/?$',
        views.admin_edit_grant_date,
        name='admin_edit_grant_date'),
    url(r'^admin/sos_apps/?$',
        views.admin_grant_app_list,
        name='admin_sos_grant_app_list'),
    url(r'^admin/sos_apps/app-(?P<grant_app_id>\d+)/?$',
        views.admin_grant_app_detail,
        name='admin_sos_grant_app_detail'),
    #also add a url for archived seasons
)

webapps2/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns(
    '',
    # Examples:
    # url(r'^$', 'webapps2.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^', include('home.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^appointments/', include('appointments.urls')),
    url(r'^organization-manager/', include('organizations.urls')),
    url(r'^organizations/', include('organizations.urls')),
    url(r'^finance/', include('finance.urls')),
    url(r'^fundingpoll/', include('fundingpoll.urls')),
    url(r'^identitypoll/', include('identitypoll.urls')),
    url(r'^elections/', include('elections.urls')),
    url(r'^sos_grant/', include('sos_grant.urls', namespace="sos_grant")),
    url('logout', 'generic.views.logout'))

sos_grant/models.py
from django.db import models
from generic.models import SinUser
from django.utils.safestring import mark_safe
# Create your models here.

from django.utils import timezone

YEARS = ((0, 'Freshman'), (1, 'Sophomore'), (2, 'Junior'), (3, 'Senior'))


class SOSGrantDates(models.Model):
    '''
    a model to hold the start and end dates for a "season" of SOS Grants
    '''

    name = models.CharField(
        blank=True, max_length=140, default="SOS Grant Dates")
    start_date = models.DateTimeField()
    end_date = models.DateTimeField()

    created_on = models.DateTimeField(auto_now_add=True)
    modified_on = models.DateTimeField(auto_now=True)

    @property
    def can_apply(self):
        '''
      returns true if the application period is open
      '''
        today = timezone.now()
        return self.start_date < today and self.end_date < today


class SOSGrantApp(models.Model):
    '''
    the individual SOS Grant application
    '''
    applicant = models.OneToOneField(SinUser, null=True)
    name = models.CharField(max_length=100)
    preferred_pron = models.CharField(
        max_length=30, blank=True, verbose_name="Preferred Pronouns")
    major = models.CharField(max_length=30)
    year = models.IntegerField(max_length=1, choices=YEARS)

    #contact info
    address = models.CharField(max_length=50)
    phone = models.CharField(max_length=15)
    email = models.EmailField()

    #app info
    created_on = models.DateTimeField(auto_now_add=True)
    modified_on = models.DateTimeField(auto_now=True)
    sos_grant_dates = models.ForeignKey(SOSGrantDates)

    #questions...
    #Internships / Short Term Employment OR Conference/Activity Based
    INTERN = 'I'
    CONF = 'C'
    OPP_CHOICES = ((INTERN, 'Internship or short term employment'),
                   (CONF, "Conference or activity-based opportunity"))
    opp_choice = models.CharField(max_length=1, null=True, choices=OPP_CHOICES, \
                                  verbose_name="For what type of opportunity are you applying for assistance?",\
                                  help_text=mark_safe("If you aren't sure, contact <a href=\"sos-committee@reed.edu\">sos-committee@reed.edu</a>."))

    #internship or short employment section
    #questions if the user chooses INTERN/ 'I'
    pos_title = models.CharField(blank=True, max_length=140, verbose_name="What is the title of your position?",\
                                 help_text="(for all of these questions, if you don't know yet, give us your best guess)")
    comp_name = models.CharField(
        blank=True,
        max_length=140,
        verbose_name="What is the name of your company/employer?")
    hours = models.CharField(
        blank=True,
        max_length=140,
        verbose_name="What is the hourly commitment of the internship or short-term employment?"
    )
    salary = models.CharField(
        blank=True,
        max_length=140,
        verbose_name="What is your (expected) salary for the position?")
    supervisor = models.TextField(blank=True, verbose_name="Who is your supervior for the position? Please provide relevant contact information.", \
                                  help_text="This can also be your point of contact if you don't know who your supervisor would be yet")

    #questions if the user chooses CONF/'C'
    conf_title = models.CharField(blank=True, max_length=140, verbose_name="What is the name of the conference or activity?",\
                                 help_text="(for all of these questions, if you don't know yet, give us your best guess)")
    role = models.TextField(
        blank=True,
        verbose_name="What is your role/involvement in the conference or activity?"
    )
    start_date = models.TextField(
        blank=True,
        verbose_name="What is the starting date and duration of the conference or activity?"
    )
    contact = models.TextField(blank=True, verbose_name="Who is your contact person for this conference or activity-based opportunity?"\
                                              " Please provide relevant contact information.")

    #question for both choices I/C
    description = models.TextField(verbose_name="Please describe your tasks and responsibilities in your summer role," \
                                          " how this role might influence your Reed education," \
                                          " and other reasons why the committee should recommend allocating grant" \
                                          " money towards your summer opportunity. In your application, the SOS committee" \
                                          " will also consider whether or not there are pre-existing sources of funding" \
                                          " in pursuing similar opportunities. If there are other sources of financial" \
                                          " support for this opportunity that you have chosen to not explore, please elaborate on that choice here.",\
                                          help_text="(If you haven't looked for money, go do that! Contact career services!"\
                                          " We don't have very much money, and a lot of people want our money-" \
                                          " the more money you take from other sources, the more people we can help!)")

    # #funding section
    acad_fund = models.TextField(verbose_name="Have you sought funding from an academic department?", \
                                  help_text="If so, what was the outcome? (let us know if you're waiting to hear back, also!)")
    ss_fund = models.TextField(verbose_name="Have you sought funding from Student Services?", \
                                  help_text="If so, what was the outcome? (let us know if you're waiting to hear back, also!)")
    clbr_fund = models.TextField(verbose_name="Have you sought funding from The Center for Life Beyond Reed (Career Services)?",\
                                  help_text="If so, what was the outcome? (let us know if you're waiting to hear back, also!)")
    other_fund = models.TextField(verbose_name="Have you sought funding from other resources on campus?",\
                                  help_text="If so, what was the outcome? (let us know if you're waiting to hear back, also!)")
    funds = models.DecimalField(default=0.0, verbose_name="What is the total amount of funding you have received from other sources at Reed?",\
                                  max_digits = 8, decimal_places = 2)
    explain = models.TextField(blank=True, verbose_name="The SOS Committee will be in contact with the Business Office about your financial status." \
                                            " If you have financial need that would not necessarily be reflected in this information,"\
                                            " please explain the circumstances below.",\
                               help_text=mark_safe("If you have any questions, please email <a href=\"sos-committee@lists.reed.edu\">sos-committee@lists.reed.edu</a>"))
    proposal = models.TextField(verbose_name=mark_safe("If you'd prefer to write your proposal directly in the application, you may do so here."\
                                            " If not, please send it to <a href=\"sos-committee@reed.edu\">sos-committee@reed.edu</a>."))

    def meta(self):
        return self._meta

    def visible_attrs(self):
        for field in self._meta.fields:
            if field.name != "id" and field.name != "created_on" and field.name != "modified_on" and field.name != "sos_grant_dates":
                print(field.name)
                yield field.verbose_name, getattr(self, field.name)

    def attrs(self):
        for field in self._meta.fields:
            yield field.verbose_name, getattr(self, field.name)

    #ensure that only one application can be submitted per student
    # class Meta:
    # unique_together = ("applicant", "sos_grant_dates")

sos_grant/forms.py
from django import forms

# imports for modelform
from django.forms import ModelForm
from .models import SOSGrantDates, SOSGrantApp
from django.forms.widgets import DateTimeInput, SplitDateTimeWidget
from django.core.exceptions import ValidationError
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout, Field, Fieldset
from crispy_forms.bootstrap import PrependedText

# def validate_date():
#form availaible to ADMINS

# def validate_date(self):
#   print(self)
#   print("validate_date")


class SOSGrantDatesForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(SOSGrantDatesForm, self).__init__(*args, **kwargs)

        # If you pass FormHelper constructor a form instance
        # It builds a default layout with all its fields
        self.helper = FormHelper(self)
        # self.helper.form_tag = False
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-sm-2'
        self.helper.field_class = 'col-sm-10'
        self.helper.layout = Layout(
            Field('name'),
            PrependedText(
                'start_date',
                '<span class=\"glyphicon glyphicon-time\" aria-hidden=\"true\"></span>',
                placeholder="mm-dd-yyyy hr:min"),
            PrependedText(
                'end_date',
                '<span class=\"glyphicon glyphicon-time\" aria-hidden=\"true\"></span>',
                placeholder="mm-dd-yyyy hr:min"), )
        self.helper.layout.append(
            Submit(
                'submit',
                'Submit',
                css_class="btn btn-lg btn-primary btn-block form-control"))

    class Meta:
        model = SOSGrantDates
        fields = ('name', 'start_date', 'end_date')
        localized_fields = ('start_date', 'end_date')


#form availiable to applicants
class SOSGrantAppForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(SOSGrantAppForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper(self)
        # self.helper.form_class = 'form-horizontal'
        # self.helper.label_class = 'col-sm-2'
        # self.helper.field_class = 'col-sm-10'
        self.helper.form_id = "sos_grant_form"
        self.helper.layout = Layout(
            Fieldset(
                '(tell us about you)',
                'name',
                'preferred_pron',
                'major',
                'year',
                'address',
                'phone',
                'email', ),
            Fieldset('Opportunity Type', 'opp_choice'),
            Fieldset(
                'Internship or Employment Opportunity',
                'pos_title',
                'comp_name',
                'hours',
                'salary',
                'supervisor',
                id="intern_section"),
            Fieldset(
                'Conference or Activity-Based Opportunity',
                'conf_title',
                'role',
                PrependedText(
                    'start_date',
                    '<span class=\"glyphicon glyphicon-calendar\" aria-hidden=\"true\"></span>',
                    placeholder="mm-dd-yyyy, or whatever you know"),
                'contact',
                id="conf_section", ),
            Fieldset('Tell us more', 'description'),
            Fieldset('Funding', 'acad_fund', 'ss_fund',
                     'clbr_fund', 'other_fund',
                     PrependedText('funds', '$'), 'explain'), 'proposal')
        self.helper.layout.append(
            Submit(
                'Save & Submit',
                'Save & Submit',
                css_class="btn btn-lg btn-primary btn-block form-control"))

    class Meta:
        model = SOSGrantApp
        exclude = ('applicant', 'created_on', 'modified_on', 'sos_grant_dates')

        # self.fields['mydate'].widget = widgets.AdminDateWidget()
        # self.fields['mytime'].widget = widgets.AdminTimeWidget()
        # self.fields['mydatetime'].widget = widgets.AdminSplitDateTime()

templates/sos_grant/admin_application_detail_view.html
{% extends "sos_grant/sos_grant-base.html" %}

{% block content %}
<div class="row">
<div class="col-sm-12">
  <h2 class=""> SOS Grant Dates
   <span class="text-muted smaller">(due dates)</span>
  </h2>
  <p class="lead">
        <span class="name">{{ sos_app.name}}</span> is a <strong>
        {% ifequal sos_app.year 0 %}
        Freshman</strong>,
        {% endifequal %}
        {% ifequal sos_app.year 1 %}
        Sophomore</strong>,
        {% endifequal %}    
        {% ifequal sos_app.year 2 %}
        Junior</strong>,
        {% endifequal %}    
        {% ifequal sos_app.year 3 %}
        Senior</strong>,
        {% endifequal %}
  Majoring in <strong>{{sos_app.major}}</strong>.
  </p>
  <p> You can email <span class="name">{{sos_app.name}}</span> about this application at 
    <a href="mailto:{{sos_app.email}}?Subject=Your%20{{sos_app.position.name}}%20Application">{{sos_app.email}}</a>.
  </p>
</div> <!-- /.col-lg-5 ... -->
<div class="col-sm-12">
 <p class="lead">&nbsp;</p> <!-- for aesthetics / alignment -->
 <div class="table-responsive">
  <table class="table table-hover">
    <thead class="table-header">
      <td class="col-sm-5"><b>Question</b></td>
      <td><b>Response</b></td>
    </thead>
    {% for question, answer in sos_app.visible_attrs %}
    <tr>
      <td class="col-sm-5">{{question}}</td>
      <td>{{answer}}</td>
    </tr>
    {% endfor %}
        <!-- <tr>
      <td class="table-header">Preferred Pronouns</td>
      <td>{{sos_app.preferred_pron}}</td>
    </tr>
    <tr>
      <td class="table-header">Phone</td>
      <td>{{sos_app.phone}}</td>
    </tr>
    <tr>
      <td class="table-header">Address</td>
      <td> {{ sos_app.address }} </td>
    </tr>
    <!- which section did they select -->
<!--     <tr>
      <td class="table-header"> Opportunuty Type</td>
      <td> {{sos_app.schedule_conflicts|safe}} </td>
    </tr>

    <tr>
      <td class="table-header"> </td>
      <td> {{sos_app.schedule_conflicts|safe}} </td>
    </tr>
    <tr>
      <td class="table-header"> Other Reed Positions </td>
      <td> {{sos_app.other_reed_positions|safe}} </td>
    </tr>
    <tr>
      <td class="table-header"> Other Employment </td>
      <td> {{sos_app.other_employment|safe}}</td>
    </tr>
    <tr>
      <td class="table-header"> Experience </td>
      <td> {{ sos_app.experience }}</td>
    </tr>
    <tr>
      <td class="table-header"> Motivation </td>
      <td> {{ sos_app.motivation }}</td>
    </tr>
    <tr>
      <td class="table-header"> Special Skills </td>
      <td> {{ sos_app.special_skills }}</td>
    </tr>
    <tr>
      <td class="table-header"> Additional Comments </td>
      <td> {{ sos_app.appeal }}</td> -->
  </table>
 </div>
</div> <!-- /.col-md-8 ... -->
</div> <!-- /.row -->
{% endblock %}

templates/sos_grant/admin_application_list_view.html
{% extends "sos_grant/sos_grant-base.html" %}

{% block content %}
<div class="row-extra-padding">
  <p class="lead">
    <span class="glyphicon glyphicon-dashboard"></span>
    Welcome <span class="text-muted">to the SOS Grant Admin Dashboard.</span>
  </p>
<hr class="featurette divider">
{% include "includes/messages.html" %}
{% if grant_date %}
  <h2>Applications <span class="text-muted">for {{grant_date.name}}</span></h2>
</div>

<table class="table table-hover">
  <thead class="table-header">
    <td>Applicant Name</td>
    <td>Last Modified</td>
    <td>Action</td>
  </thead>
      {% for app in grant_apps %}
    <tr>
    <td>{{ app.applicant.get_full_name }}</td>
    <td>{{ app.modified_on }}</td>
    <td>
     <button class="btn btn-primary " type="submit"
            onclick="window.location = '{% url 'sos_grant:admin_sos_grant_app_detail' app.id %}/';">
      <span class="glyphicon glyphicon-eye-open"></span>&nbsp; View Application
     </button>
    </td>
  </tr>
  {% empty %}
    <tr>
    <td>Sorry, there have been no applications at this time.</td>
  </tr>
{% endfor %}
</table>
{% endif %}

{% endblock %}

templates/sos_grant/admin_edit_grant_date.html
{% extends "sos_grant/sos_grant-base.html" %}

{% block content %}
{% include "includes/messages.html" %}
<div class="row-extra-padding">
  <div class="col-md-7 col-sm-12">
  <p class="lead">
    <span class="glyphicon glyphicon-dashboard"></span>
    Welcome <span class="text-muted">to the SOS Grant Admin Dashboard.</span>
    <p class="lead"> this is the place to edit grant periods. extend deadlines. go wild!</p>
    <p class="helptext help-block">Hover to the left of the boxes to see the datepicker. The system is a little picky... we're hoping to get a date & time with the format mm/dd/yyyy, --:-- --. For example: 04/20/2420, 04:20 AM</p>
  </p>
  <hr class="featurette-divider">
</div>
<div class="row-extra-padding">
<!-- <div class="row-extra-padding"> -->
  <div class="col-md-7 col-sm-12">
    {% load crispy_forms_tags %}
    {% crispy grant_form grant_form.helper %}
    <!-- <form class="form-horizontal" action="{% url 'sos_grant:admin_edit_grant_date' %}" method="post" role="form">
    {% csrf_token %}
    <div class="form-group">
        <label class="control-label col-sm-2" for="id_name">Name:</label> 
        <div class="col-sm-10"> 
        <input class="form-control" id="id_name" maxlength="140" name="name" type="text" value="SOS Grant Dates" />
        <span class="helptext help-block">(The default name is "SOS Grant Dates", if that's okay, you don't need to provide a new name.)</span>
        </div>
      </div>
      <div class="form-group">
        <label class="control-label col-sm-2" for="id_start_date">Start date:</label> 
        <div class="col-sm-10">
          <div class="input-group">
            <div class="input-group-addon">
              <span class="glyphicon glyphicon-time" aria-hidden="true"></span>
            </div>
            <input class="form-control" id="id_start_date" name="start_date" type="text" {% if grant_form.start_date.value %}value="{{grant_form.start_date.value}}"{% endif %}/>
          </div>
        </div>
      </div>
      <div class="form-group">
        <label class="control-label col-sm-2" for="id_end_date">Deadline:</label> 
        <div class="col-sm-10">
          <div class="input-group">
          <div class="input-group-addon">
            <span class="glyphicon glyphicon-time" aria-hidden="true"></span>
          </div>
            <input class="form-control" id="id_end_date"  name="end_date" type="text" {% if grant_form.start_date.value %}value="{{grant_form.end_date.value}}"{% endif %}/>
          </div>
          <span class="helptext help-block">we're hoping to get a date & time with the format mm/dd/yyyy --:-- --. <br>For example: 04/20/2420, 04:20</span>
        </div>
      </div>
      <!-- to do: add days button?
<!--       <div class="col-sm-10 col-sm-offset-2"><input id="submit_sos_grant_dates" class="btn btn-lg btn-primary btn-block form-control" type="submit" value="Submit"/> -->
    <!-- </form> --> 
  </div> <!-- /.table-responsive -->
</div>
{% endblock %}

templates/sos_grant/admin_index.html
{% extends "sos_grant/sos_grant-base.html" %}

{% block content %}
<!-- {% include "includes/messages.html" %} -->
<div class="row-extra-padding">
  <p class="lead">
    <span class="glyphicon glyphicon-dashboard"></span>
    Welcome <span class="text-muted">to the SOS Grant Admin Dashboard.</span>
  </p>
</div>
<hr>
{% include "includes/messages.html" %}
<form onsubmit="return false;">
<table class="table table-hover table-responsive">
  {% if grant_period %} 
  <thead class="table-header">
    <th>Num Apps</th>
    <th>Applications Open</th>
    <th>Application Deadline</th>
    <th>Created On</th>
    <th>Manage Grant Applications</th>
  </thead>
  <tr>
    <td>{{ grant_period.sos_grant_app_set }}</td>
    <td>{{ grant_period.start_date|date:"m-d-Y" }}</td>
    <td>{{ grant_period.end_date|date:"m-d-Y" }}</td>
    <td>{{ grant_period.created_on|date:"m-d-Y" }}</td>
    <td>
      <button type="submit" class="btn btn-primary btn-sm"
               onclick="window.location = '{% url 'sos_grant:admin_sos_grant_app_list'%}';">
        <span class="glyphicon glyphicon-eye-open"></span>&nbsp;View Applications
      </button>
    &nbsp;
      <button type="submit" class="btn btn-primary btn-sm"
               onclick="window.location = '{% url 'sos_grant:admin_edit_grant_date'%}';">
        <span class="glyphicon glyphicon-pencil"></span>&nbsp;Edit Deadlines
      </button>
    &nbsp;
    </td>
  </tr>
  {% else%}
    <td colspan=5>
      <button type="submit" class="btn btn-primary btn-block"
               onclick="window.location = '{%url 'sos_grant:admin_create_grant_date'%}';">
        <span class="glyphicon glyphicon-plus"></span>&nbsp;&nbsp;Start a new grant period 
      </button>
    </td>
  </tr>
  {% endif %}
</table>
</form>
{% endblock %}

templates/sos_grant/create_application.html
{% extends "sos_grant/sos_grant-base.html" %}

{% block content %}
<div class="row-extra-padding">
  <div class="col-md-7 col-sm-7">
    <h2 class="featurette-heading">
        apply for a student opportunity grant
    </h2>
    <p class="text-muted">fill out this form </p>
  </div>
</div>
<form method="post" action="">
{% csrf_token %}
<table>
{{sos_form}}
</table>
<input type="submit" value="Submit Form"/>
</form>
{% endblock %}

templates/sos_grant/index.html
{% extends "sos_grant/sos_grant-base.html" %}

{% block content %}
{% include "includes/messages.html" %}
<div class="row-extra-padding">
  <div class="col-md-7 col-sm-7">
    <h2 class="featurette-heading">
        welcome to the student opportunity grant webapp
    </h2>
    <hr class="featurette-divider">
    <h2 class="featurette-heading">The Hopes and Dreams of the Committee:</h3>
    <blockquote>
        <ul class="list-unstyled">
        <li>The committee prioritizes applicants who have a clear sense of direction with their project, express enthusiasm, and can enumerate different directions that their project may take.</li>
        <li>The committee prioritizes applicants whose projects will supplement their intellectual and/or emotional development, while also expanding their boundaries beyond Reed and the academic sphere.</li>
        <li>The committee prioritizes students with large financial need as well as students who have either sought alternative sources of funding or who, after researching alternative sources of funding, have not found easily available funds</li> 
        <li>The committee prioritizes applicants who present reasonable budgets and who are mindful of the amount of money available for grant prizes.</li>
      </ul>
    </blockquote>
  </div>
  <!-- show one of these based on whether or not there's an app -->
</div>
<div class="row-extra-padding">
  <div class="col-md-7 col-sm-7">
  {% if grant_open %}
    {% if grant_app %}
    <a class="btn btn-default" href="{% url 'sos_grant:manage_application' %}">manage your application here &raquo;</a>
    {% else %}
    <a class="btn btn-default" href="{% url 'sos_grant:create_application' %}">apply here &raquo;</a>
    {% endif %} <!-- grant_app -->
  {% else %}
    <p> Sorry, grant apps aren't open right now! </p>
  {% endif %} <!-- grant_open -->
  </div>
</div>
{% endblock %}

templates/sos_grant/manage_application.html
{% extends "sos_grant/sos_grant-base.html" %}

{% block content %}
{% include "includes/messages.html" %}

<div class="row-extra-padding">
  <div class="col-md-12 col-sm-12">
    <h2 class="featurette-heading">
        manage your sos grant application here
    </h2>
    <div class="table-responsive">
      <table class="table table-hover table-responsive">
      <thead class="table-header">
      <td>Your Application</td>
      <td>Created On</td>
      <td>Modified On</td>
      <td> Manage </td>
      </thead>
      <tbody>
        <tr>
          <td>{{ grant_app.applicant }}</td>
          <td>{{ grant_app.created_on|date:"h:i A F d, Y" }}</td>
          <td>{{ grant_app.modified_on|date:"h:i A F d, Y" }}</td>
          <td>
            <input class="btn btn-primary btn-sm" type="submit" value="Edit" onclick="window.location = '{% url 'sos_grant:edit_application' %}';"/>

            <input class="btn btn-primary btn-sm" type="submit" value="Delete" onclick="var c = confirm('Are you sure you wish to delete this application?'); if (c) { window.location = '{% url 'sos_grant:delete_application' %}';}"/>
          </td>
        </tr>
      </tbody>
      </table>
    </div>
  </div>
</div>
{% endblock %}

templates/sos_grant/sos_grant-base.html
{% extends "bb-base.html" %}

{% block stylesheets %}
{% load static %}
<!-- <link rel="stylesheet" href="{% static 'bb-redux/bb-finance.css' %}" /> -->
{% endblock %}

{% block html-title %}sos-grant{% endblock %}

{% block fancy-header %}sos-grant{% endblock %}